{
  "headers": {
    "client_id": "12345",
    "client_secret": "12345",
    "content-type": "application/json",
    "user-agent": "PostmanRuntime/7.40.0",
    "accept": "*/*",
    "cache-control": "no-cache",
    "postman-token": "c607b08f-40ae-43ac-839a-039b54395bd7",
    "host": "localhost:8081",
    "accept-encoding": "gzip, deflate, br",
    "connection": "keep-alive",
    "content-length": "49"
  },
  "clientCertificate": null,
  "method": "POST",
  "scheme": "http",
  "queryParams": {},
  "requestUri": "/api/employees",
  "queryString": "",
  "version": "HTTP/1.1",
  "maskedRequestPath": "/employees",
  "listenerPath": "/api/*",
  "localAddress": "/127.0.0.1:8081",
  "relativePath": "/api/employees",
  "uriParams": {},
  "rawRequestUri": "/api/employees",
  "rawRequestPath": "/api/employees",
  "remoteAddress": "/127.0.0.1:58345",
  "requestPath": "/api/employees"
}