{
  "headers": {
    "client_id": "12345",
    "client_secret": "12345",
    "content-type": "application/json",
    "user-agent": "PostmanRuntime/7.40.0",
    "accept": "*/*",
    "cache-control": "no-cache",
    "postman-token": "76ca173f-fea2-41f8-a425-73f14c18438d",
    "host": "localhost:8081",
    "accept-encoding": "gzip, deflate, br",
    "connection": "keep-alive",
    "content-length": "50"
  },
  "clientCertificate": null,
  "method": "GET",
  "scheme": "http",
  "queryParams": {},
  "requestUri": "/api/employees",
  "queryString": "",
  "version": "HTTP/1.1",
  "maskedRequestPath": "/employees",
  "listenerPath": "/api/*",
  "relativePath": "/api/employees",
  "localAddress": "/127.0.0.1:8081",
  "uriParams": {},
  "rawRequestUri": "/api/employees",
  "rawRequestPath": "/api/employees",
  "remoteAddress": "/127.0.0.1:54570",
  "requestPath": "/api/employees"
}